# =================================
# SERVICE CONFIGURATION
# =================================
spring:
  application:
    name: SATIC-ONLINE-SHOP-REGISTRY-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
    profiles:
      active: prod
